server/views/auth_views.py
import functools
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from server import db
from server.forms import UserLoginForm
from server.models import User

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login/", methods=("GET", "POST"))
def login():
    form = UserLoginForm()

    if request.method == "POST" and form.validate_on_submit():
        error = None
        user = User.query.filter_by(user_id=form.user_id.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."

        if error is None:
            session.clear()
            session["user_id"] = user.user_id
            _next = request.args.get("next", "")
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for("page.dashboard"))

        flash(error)

    return render_template("auth/login.html", form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route("/signup/")
def signup():
    form = UserLoginForm()
    
    if request.method == "GET":
        print("GET 요청왓음ㅇㅇ")
        user = User.query.filter_by(user_id="admin").first()
        if not user:
            user = User(
                user_id="admin",
                # auth_id="admin",
                password=generate_password_hash("admin"),
            )
            db.session.add(user)
            db.session.commit()
        else:
            flash('이미 생성되었음')
    
    return redirect(url_for('auth.login'))


@bp.route("/logout/")
def logout():
    session.clear()
    return redirect(url_for('adm.index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        
        return view(*args, **kwargs)
   
    return wrapped_view

server/views/yolo_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g, jsonify
from flask import make_response, send_from_directory
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from server import db
from server.forms import UserCreateForm, UserDetailForm
from server.models import Img_set, Tag_set, Medicine, Check_log, ID_seq, Model_list
from server.views.auth_views import login_required

from sqlalchemy import func

import os

# 데이터셋으로 이용하던 이미지를 제거하는 경우
def del_tag(img_id):
    # 사용 예시
    # /static/yolo_model/datasets/train/images/image-0.jpg
    # /static/image/202311/IMG_00005951_20231120_151321.png

    head = './server'
    label_path = '/static/yolo_model/datasets/train/labels/'

    img_query = Img_set.query.get(img_id)

    img_name = img_query.img_dir.split("/")[-1]
    try:
        seq_name, seq, yyyymmdd, picture = img_name.split("_")
        img_path = f"/static/image/{yyyymmdd[:-2]}/"

    except:
        img_path = "/static/image/default/"    

    

    # img 폴더에 저장되어있던 이미지 파일을
    # dataset 폴더로 이동
    os.replace(head + img_query.img_dir, head + img_path + img_name)
    
    # 이동한 이미지의 경로를 업데이트
    img_query.img_dir = img_path + img_name
    db.session.commit()
    
    # 태그를 입력하기 위한 파일을 open
    tag_file = f'{head + label_path + img_name.split(".")[0]}.txt'
    try:
        os.remove(tag_file)
    except:
        print("file none")

# 태그로 이용 할 수 있게 DB의 데이터를 텍스트파일로 저장함
def tag_to_txt(img_id):
        
    # 사용 예시
    # /static/yolo_model/datasets/train/images/image-0.jpg
    # /static/image/202311/IMG_00005951_20231120_151321.png
    head = './server'
    label_path = '/static/yolo_model/datasets/train/labels/'
    img_path = '/static/yolo_model/datasets/train/images/'

    img_query = Img_set.query.get(img_id)

    img_name = img_query.img_dir.split("/")[-1]

    # img 폴더에 저장되어있던 이미지 파일을
    # dataset 폴더로 이동
    os.replace(head + img_query.img_dir, head + img_path + img_name)
    
    # 이동한 이미지의 경로를 업데이트
    img_query.img_dir = img_path + img_name
    db.session.commit()
    
    # 태그를 입력하기 위한 파일을 open
    tag_file = f'{img_name.split(".")[0]}.txt'
    f = open(head + label_path + tag_file, "w")

    # 6 0.388875 0.497333 0.617250 0.486000
    for tag in Tag_set.query.filter(Tag_set.img_id == img_id).all():
        tag_list = list(map(str, [tag.class_id, tag.x, tag.y, tag.width, tag.height]))
        f.write(" ".join(tag_list))
        f.write("\n")
    
    f.close()

# 의약품 키워드를 기반으로 의약품의 class id를 추출
def get_id_from_keyword(keyword):
    search = "%%{}%%".format(keyword)

    # 키워드를 기반으로 class_id를 추출함
    id_list = []
    for item in Medicine.query.filter(Medicine.name.ilike(search)).all():
        id_list.append(item.class_id)

    subquery = Tag_set.query.filter(Tag_set.class_id.in_(id_list)).subquery()
    using_dataset = db.session.query(
        Img_set.img_id,
        Img_set.user_id,
        Img_set.img_dir,
        Img_set.train_cnt,
        Img_set.date,
        Img_set.rate,
        Img_set.train_yn
    ).select_from(Img_set).join(
        subquery, Img_set.img_id == subquery.c.img_id
    ).group_by(subquery.c.img_id)

    return using_dataset

bp = Blueprint("model", __name__, url_prefix="/model")

# 현재 사용중인 학습 데이터셋과 사용중이지 않은 데이터셋을 출력
@bp.route("/data_list/", methods=['GET', 'POST'])
@login_required
def data_list():
    
    params = request.form
    y_keyword = ""
    n_keyword = ""

    print(params)
    # 키워드가 존재한다면 전달받음
    if(request.method =='POST'):
        y_keyword = params['yKeyword']
        n_keyword = params['nKeyword']
    
    # 현재 사용중인 데이터셋 추출
    using_dataset = Img_set.query.filter(Img_set.train_yn == "Y")
    subquery = Img_set.query.filter(Img_set.train_yn == "N").subquery()

    # 키워드가 존재한다면 검색 결과를 출력함
    if y_keyword:
        using_dataset = get_id_from_keyword(y_keyword)

        subquery = using_dataset.filter(Img_set.train_yn == "N").subquery()
        using_dataset = using_dataset.filter(Img_set.train_yn == "Y")
        
    using_dataset = using_dataset.paginate(page=1, per_page=50)

    # 의약품 목록 추출
    medicine_list_using = Medicine.get_using()

    # 미사용 목록 추출
    
    n_dataset = db.session.query(
        subquery.c.img_id,
        subquery.c.date,
        subquery.c.rate,
        subquery.c.train_cnt,
        subquery.c.train_yn
    ).join(
        Tag_set, Tag_set.img_id == subquery.c.img_id
    ).group_by(subquery.c.img_id)

    n_dataset = n_dataset.paginate(page=1, per_page=50)

    return render_template("model/data_list.html", 
                           current_menu="data_list",
                           using_dataset = using_dataset,
                           n_dataset = n_dataset,
                           yKeyword = y_keyword,
                           nKeyword = n_keyword,
                           medicine_list_using = medicine_list_using)

# 데이터셋 검색 및 페이지 넘기기 기능
@bp.route("/data_q_list/<string:train_yn>/<int:page>/<string:keyword>")
@bp.route("/data_q_list/<string:train_yn>/<int:page>/")
@login_required
def data_q_list(page, train_yn, keyword = ""):
    print(page, train_yn)

    # 사용 여부에 따른 쿼리
    dataset = get_id_from_keyword(keyword).filter(Img_set.train_yn == train_yn)
    
    # 데이터 페이징
    dataset = dataset.paginate(page=page, per_page=15)

    resp = {
        "resp" : 200,
        "data" : []
    }

    #출력 데이터 양식
    for item in dataset.items:
        resp["data"].append({
            "img_id" : item.img_id,
            "train_yn" : item.train_yn,
            "train_cnt" : item.train_cnt
        })

    return jsonify(resp)

# 사용여부 변경 (data_list에서 데이터 추가 및 제거 버튼)
@bp.route("/yn_change/", methods = ['POST'])
@login_required
def yn_change():
    
    print(request)
    
    data = request.get_json()
    
    if data['now'] == "Y":
        to_change = "N"
        
    elif data['now'] == "N":
        to_change = "Y"

    else:
        return make_response("fail", 403)
    
    for img in Img_set.query.filter(Img_set.img_id.in_(data['data'])).all():
        img.train_yn = to_change

        if to_change == "N":
            del_tag(img.img_id)

        if to_change == "Y":
            tag_to_txt(img.img_id)


    db.session.commit()

    return make_response("success", 200)

# 데이터셋의 태그를 수정하는 페이지
@bp.route("/data_tag/")
@login_required
def data_tag():
    
    page = request.args.get("page", type=int, default=1)
    kw = request.args.get("kw", type=str, default="")
    using_dataset = Img_set.query.filter(Img_set.train_yn == "Y")

    # 키워드가 존재하면 검색결과를 출력함
    if kw:
        using_dataset = get_id_from_keyword(kw)

    using_dataset = using_dataset.paginate(page=page, per_page=10)

    # 현재 사용중인 class_id 추출, 검색어 자동완성에 사용됨
    medicine_list_using = Medicine.get_using()
    # medicine_list_all = medicine_list.all()

    return render_template("model/data_tag.html", 
                           current_menu="data_tag",
                           using_dataset = using_dataset,
                           page = page,
                           kw = kw,
                           medicine_list_using = medicine_list_using
                           )

# 구체적인 해당 img_id의 태그 정보를 불러옴
@bp.route("/data_detail/<img_id>")
@login_required
def data_detail(img_id):
    
    img_dir = Img_set.query.filter(Img_set.img_id == img_id).first().img_dir
    subquery = Tag_set.query.filter(Tag_set.img_id == img_id).subquery()
    
    # 이미지 id가 같은 tag 정보를 img와 join
    tag_list = db.session.query(
        subquery.c.tag_id,
        subquery.c.x,
        subquery.c.y,
        subquery.c.width,
        subquery.c.height,
        subquery.c.class_id,
        Medicine.name
    ).join(
        Medicine, Medicine.class_id == subquery.c.class_id
    )

    print(tag_list.statement)
    
    tag_list = tag_list.all()

    # 결과 form
    response_list = {
        'id': img_id,
        'path': img_dir,
        'data':[]
    }

    if tag_list is None:
        return jsonify({'error': '태그 정보를 찾을 수 없습니다.'}), 404

    # 결과 입력
    for tag in tag_list:
        
        response_list['data'].append({
            'tag_id': tag.tag_id,
            'name' : tag.name,
            'left': tag.x,
            'top': tag.y,
            'width': tag.width,
            'height': tag.height,
            'class_id': tag.class_id
        })
    
    print(response_list)
    return response_list

# 사용할 모델 설정
@bp.route("/data_learning/")
@login_required
def data_learning():
    page = request.args.get("page", type=int, default=1)

    model_list = Model_list.query.paginate(page=page, per_page=10)
    
    return render_template("model/data_learning.html",
                           current_menu="data_learning",
                           model_list = model_list
                           ) 

# 서버 모델 학습
@bp.route("/learning/", methods = ['POST'])
@login_required
def learning():
    
    from ultralytics import YOLO

    model = YOLO()

    model_id = ID_seq.call_ID("MOD")

    # yaml 파일 저장
    yaml = open("./server/static/yolo_model/data.yaml", "w", encoding="utf-8")
    
    # class_id 순서대로 정렬
    using_list = sorted(Medicine.get_using(), key=lambda x: int(x[0]))

    # 약품 이름만 추출
    using_list = [item[1] for item in using_list]

    yaml.write("\n".join([
        "train: ./datasets/train",
        "val: ./datasets/valid",
        "",
        f"nc: {len(using_list)}",
        "",
        f"names: {using_list}"
    ]))

    yaml.close()

    # 모델 학습결과 저장
    result = model.train(data='./server/static/yolo_model/data.yaml' , epochs=1, patience=50,  project="server/static/yolo_model", name=model_id)
    
    # 새로운 파일 이름 생성
    from datetime import datetime

    pt_dir = str(result.save_dir)
    pt_dir = f'./{pt_dir}/weights/best.pt'

    # 평균 정확도
    mean_rate = result.maps.mean()

    # 클래스별 정확도 결과 리스트
    maps = ",".join(str(value) for value in result.maps)

    # DB 저장
    Model_list.add_model(model_id, pt_dir, mean_rate, maps)

    try:
        resp = {
            "resp" : 200,
            "data" : result

server/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">

    <!-- Bootstrap Icon-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    <!-- pybo CSS -->
    <!--
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    -->

    <title>KnowMedicine 관리자 시스템</title>
</head>

<body>

    <div class="row m-0">
        {% include "sidebar.html" %}

        <div class="col">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}">
    </script>


    <!-- Chart.js -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.min.js"></script> -->
    
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->

</body>

</html>

server/templates/form_errors.html
<!-- 필드 오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}

<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

server/templates/sidebar.html
<!-- Sidebar  -->
<div class="d-flex flex-column p-3 text-white bg-dark min-vh-100" style="width:300px;">
    
    <!-- 아이콘과 로고 -->
    <div class="p-3 d-flex align-items-center mb-10 mb-md-0 me-md-auto text-white text-decoration-none">
        <span class="fs-4 fw-bold">
            <i class="bi bi-capsule me-2"></i>KnowMedicine
        </span>
    </div>

    <hr>

    <!-- 관리자 아이디 -->
    <div class="p-3">
        {% if g.user %}
        <div class="row d-flex align-items-center">
            <div class="col-auto">
                <span class="fs-5">{{ g.user.user_id }}</span>
            </div>
    
            <div class="col text-end">
                <a href="javascript:void(0)" data-uri="{{ url_for('auth.logout') }}" class="logout btn btn-secondary btn-sm">
                    로그아웃
                </a>
            </div>
        </div>
        {% endif %}
    </div>

    <hr>

    <ul class="nav nav-pills flex-column mb-auto">
        <!-- 메뉴 항목 -->
        <li class="nav-item">
            <a href="{{ url_for('page.dashboard') }}" class="nav-link {% if current_menu == 'dashboard' %} active {% else %} text-white {% endif %}" aria-current="page">
                <i class="bi bi-speedometer2 me-2"></i>대시보드
            </a>
        </li>
        <li>
            <a href="{{ url_for('page.medicine_list') }}" class="nav-link {% if current_menu == 'medicine_list' %} active {% else %} text-white {% endif %}">
                <i class="bi bi-prescription2 me-2"></i>의약품 관리
            </a>
        </li>
        <li>
            <a href="{{ url_for('page.user_list') }}" class="nav-link {% if current_menu == 'user_list' %} active {% else %} text-white {% endif %}">
                <i class="bi bi-person-fill me-2"></i>유저 관리
            </a>
        </li>
        <li>
            <a href="{{ url_for('model.analysis_log') }}" class="nav-link {% if current_menu == 'analysis_log' %} active {% else %} text-white {% endif %}">
                <i class="bi bi-file-earmark-text me-2"></i>분석 로그
            </a>
        </li>
        <li>
            <a href="{{ url_for('model.data_list') }}" class="nav-link {% if current_menu == 'data_list' %} active {% else %} text-white {% endif %}">
                <i class="bi bi-gear-wide-connected me-2"></i>데이터 관리
            </a>
        </li>
        <li>
            <a href="{{ url_for('model.data_learning') }}" class="nav-link {% if current_menu == 'data_learning' %} active {% else %} text-white {% endif %}">
                <i class="bi bi-gear-wide-connected me-2"></i>모델 목록
            </a>
        </li>
        <li>
            <a href="{{ url_for('model.data_tag') }}" class="nav-link {% if current_menu == 'data_tag' %} active {% else %} text-white {% endif %}">
                <i class="bi bi-tags-fill me-2"></i>데이터 태깅
            </a>
        </li>
    </ul>
</div>

<script type="text/javascript">

    /* 로그아웃 확인 */
    const logout_elements = document.getElementsByClassName("logout");
    Array.from(logout_elements).forEach(function (element) {
        element.addEventListener('click', function () {
            if (confirm("로그아웃 하시겠습니까?")) {
                location.href = this.dataset.uri;
            }
        });
    });

</script>