server/views/page_views.py
from io import BytesIO, StringIO
import json
from urllib.parse import quote
from flask import Blueprint, url_for, render_template, flash, request, session, g, jsonify, Response, send_file
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from server import db
from server.forms import UserCreateForm, UserDetailForm
from server.models import Medicine, Tag_set, User, Check_log
from server.views.auth_views import login_required
from sqlalchemy import desc, func, cast, Integer

from datetime import datetime, timedelta, timezone
import pandas as pd

bp = Blueprint("page", __name__, url_prefix="/page")


@bp.route("/dashboard/")
@login_required
def dashboard():
    # taggedCnt = Medicine.query.filter(Medicine.class_id != None).count()
    # nonTaggedCnt = Medicine.query.filter(Medicine.class_id == None).count()
        
    taggedCnt = db.session.query(func.count(func.distinct(Tag_set.img_id))) \
            .filter(Tag_set.img_id.in_(db.session.query(func.distinct(Check_log.img_id)))) \
            .scalar()
    nonTaggedCnt = db.session.query(func.count(func.distinct(Check_log.img_id))).scalar() - taggedCnt
    dailyUsage = get_daily_usage()
    monthlyUsage = get_monthly_usage()
    medImgs = get_med_imgs()

    return render_template("page/dashboard.html", current_menu="dashboard", 
                           taggedCnt=taggedCnt, nonTaggedCnt=nonTaggedCnt,
                           dailyUsage=dailyUsage, monthlyUsage=monthlyUsage,
                           medImgs=medImgs)


def get_daily_usage():
    end_date = datetime.utcnow()
    start_date = end_date - timedelta(days=4)
    start_date = start_date.replace(hour=0, minute=0, second=0, microsecond=0)
        
    daily_usage = db.session.query(func.date(Check_log.date).label('date'), func.count().label('count')) \
        .filter(Check_log.date >= start_date, Check_log.date <= end_date ) \
        .group_by(func.date(Check_log.date)) \
        .all()
    
    results = [(row.date.strftime('%Y-%m-%d'), row.count) for row in daily_usage]
    results = json.dumps(results)
    
    return results


def get_monthly_usage():
    end_month = datetime.utcnow().month
    start_month = end_month - 4 if end_month > 4 else 1
    
    monthly_usage = db.session.query(func.extract('month', Check_log.date).label('month'), func.count().label('count')) \
        .filter(func.extract('month', Check_log.date) >= start_month, func.extract('month', Check_log.date) <= end_month) \
        .group_by(func.extract('month', Check_log.date)) \
        .all()
        
    results = [tuple(row) for row in monthly_usage]
    results = json.dumps(results)
    
    return results


def get_med_imgs():
    # med_imgs = db.session.query(Tag_set.class_id, func.count().label('count')) \
    #     .group_by(Tag_set.class_id) \
    #     .order_by(cast(Tag_set.class_id, Integer).asc()) \
    #     .all()
    
    # med_imgs = db.session.query(Medicine.name, func.count().label('count')) \
    #     .join(Tag_set, Medicine.class_id == Tag_set.class_id) \
    #     .group_by(Medicine.name) \
    #     .order_by(cast(Tag_set.class_id, Integer).asc()) \
    #     .limit(10) \
    #     .all()
    
    subquery = db.session.query(Medicine.name, func.count().label('count')) \
        .join(Tag_set, Medicine.class_id == Tag_set.class_id) \
        .group_by(Medicine.name) \
        .order_by(desc('count')) \
        .limit(10) \
        .subquery()

    med_imgs = db.session.query(subquery.c.name, subquery.c.count) \
        .order_by(desc(subquery.c.count)) \
        .all()
    
    results = [tuple(row) for row in med_imgs]
    results = json.dumps(results)
    
    return results


@bp.route("/medicine_list/")
@login_required
def medicine_list():
    
    page = request.args.get("page", type=int, default=1)
    kw = request.args.get("kw", type=str, default="")
    
    t_medicine_list = Medicine.query.filter(Medicine.class_id != None).order_by(Medicine.name)  # class_id가 있는 약품
    nt_medicine_list = Medicine.query.filter(Medicine.class_id == None).order_by(Medicine.name) # class_id가 없는 약품 

    if kw:
        search = "%%{}%%".format(kw)
        nt_medicine_list = nt_medicine_list.filter(Medicine.name.ilike(search))
        
    nt_medicine_list = nt_medicine_list.paginate(page=page, per_page=10)
    
    return render_template("page/medicine_list.html", current_menu="medicine_list", 
                           t_medicine_list=t_medicine_list, nt_medicine_list=nt_medicine_list,
                           page=page, kw=kw)


@bp.route("/medicine_detail/<string:medId>")
def medicine_detail(medId):
    medicine = Medicine.query.get(medId)
    
    if medicine is not None:
        return jsonify({
            'name': medicine.name,
            'effect': medicine.effect,
            'usage': medicine.usage,
            'caution': medicine.caution
        })
    
    return jsonify({'error': '약품 정보를 찾을 수 없습니다.'}), 404


@bp.route("/medicine_download_csv/<string:tbType>")
def medicine_download_csv(tbType):
    # output_stream = StringIO() 
    output_stream = BytesIO() # dataframe을 저장할 IO stream
    
    if tbType == 'tagged':
        medicine_list = Medicine.query.filter(Medicine.class_id != None).order_by(Medicine.name).all()
    
    elif tbType == 'nonTagged':
        medicine_list = Medicine.query.filter(Medicine.class_id == None).order_by(Medicine.name).all()

    # DataFrame 생성
    df = pd.DataFrame({
        '의약품 이름': [medicine.name for medicine in medicine_list],
        '유형': ['키트' if medicine.effect_type == 'K' else '약품' for medicine in medicine_list],
        '효능': [medicine.effect for medicine in medicine_list],
        '용법': [medicine.usage for medicine in medicine_list],
        '주의사항': [medicine.caution for medicine in medicine_list],
    })
    
    df.to_excel(output_stream, index=False)
    output_stream.seek(0)
    
    return send_file(
        output_stream,
        mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        as_attachment=True,
        download_name=f"의약품정보_{tbType}.xlsx"
    )
    
    # df.to_csv(output_stream, encoding='utf-8-sig', index=False) # 그 결과를 앞서 만든 IO stream에 저장

    # response = Response(
    #     output_stream.getvalue(),
    #     mimetype='text/x-csv',
    #     content_type='application/octet-stream'
    # )
    
    # filename = quote("의약품정보.csv")
    # response.headers["Content-Disposition"] = f"attachment; filename*=UTF-8''{filename}"
    
    # return response
    
    # return redirect(url_for("page.medicine_list"))
    

@bp.route("/medicine_add_tag/<string:medId>")
@login_required
def medicine_add_tag(medId):    
    curMedicine = Medicine.query.filter(Medicine.med_id == medId).first()
    
    if curMedicine:
        if not curMedicine.class_id:
            tagCount = Medicine.query.filter(Medicine.class_id != None).count()
            newClassId = str(tagCount + 1)
            curMedicine.class_id = newClassId
            db.session.commit()
        else:
            print(">>> 이미 class_id 가 부여되어 있습니다.")
    else:
        print(">>> 해당 레코드를 찾을 수 없습니다.")

    return redirect(url_for("page.medicine_list"))


@bp.route("/user_list/")
@login_required
def user_list():
    page = request.args.get("page", type=int, default=1)
    kw = request.args.get("kw", type=str, default="")
    user_list = User.query.order_by(User.user_id)

    if kw:
        search = "%%{}%%".format(kw)
        user_list = user_list.filter(User.user_id.ilike(search))
        
    user_list = user_list.paginate(page=page, per_page=10)
    return render_template("page/user_list.html", current_menu="user_list", user_list=user_list, page=page, kw=kw)


@bp.route("/user_create/", methods=('GET', 'POST'))
@login_required
def user_create():
    form = UserCreateForm()
    
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(user_id=form.user_id.data).first()
        if not user:
            user = User(user_id=form.user_id.data,
                        password=generate_password_hash(form.password1.data),
                        name=form.name.data,
                        birthday=form.birthday.data,
                        gender=form.gender.data,
                        phone=form.phone.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('page.user_list'))
        else:
            flash('이미 존재하는 사용자입니다.')
    
    return render_template('page/user_create.html', current_menu="user_list", form=form)


@bp.route('/user_modify/<string:user_id>', methods=('GET', 'POST'))
@login_required
def user_modify(user_id):
    user = User.query.get_or_404(user_id)
    
    if request.method == 'POST':
        form = UserDetailForm()
        if form.validate_on_submit():
            form.populate_obj(user)
            db.session.commit()
            return redirect(url_for('page.user_list'))
    else:
        form = UserDetailForm(obj=user)
        
    return render_template('page/user_modify.html', current_menu="user_list", form=form)


@bp.route('/user_detail/<string:userId>')
def user_detail(userId):
    user = User.query.get(userId)
    # check_log = Check_log.query.filter_by(user_id=userId).order_by(desc(Check_log.date)).first()
    # check_logs = Check_log.query.filter_by(user_id=userId).order_by(desc(Check_log.date)).all()
    
    subquery = Check_log.query.filter_by(user_id=userId).subquery()
    # subquery = Check_log.query.filter_by(user_id=userId).order_by(desc(Check_log.date)).limit(10).subquery()
    
    check_logs = db.session.query(
        subquery.c.rate,
        subquery.c.date,
        Medicine.name.label('medicine_name')
    ).join(Medicine, Medicine.class_id == subquery.c.class_id).order_by(desc(subquery.c.date))
    
    # if user is not None and check_log is not None:
    #     return jsonify({
    #         'name': user.name,
    #         'birthday': user.birthday,

server/templates/page/dashboard.html
{% extends 'base.html' %}
{% block content %}

<h2 class="border-bottom py-3 m-3">대시보드</h2>

<div class="p-3">
    <div class="row mb-3">
        <div class="col card me-3">
            <canvas id="avg_acc"></canvas>
        </div>
        <div class="col card me-3">
            <canvas id="tag_ratio"></canvas>
        </div>
        <div class="col card me-3">
            <canvas id="daily_usage"></canvas>
        </div>
    </div>
    <div class="row">
        <div class="col card me-3">
            <canvas id="med_img"></canvas>
        </div>
        <div class="col card me-3">
            <canvas id="monthly_usage"></canvas>
        </div>
    </div>
</div>

<div id="chartData" data-taggedCnt="{{ taggedCnt }}" data-nonTaggedCnt="{{ nonTaggedCnt }}"
                    data-dailyUsage="{{ dailyUsage }}" data-monthlyUsage="{{ monthlyUsage }}"
                    data-medImgs="{{ medImgs }}"></div>

{% endblock %}

{% block script %}
<!-- Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.2.0"></script>

<script type="text/javascript">
    const avg_acc = document.getElementById('avg_acc');
    const tag_ratio = document.getElementById('tag_ratio');
    const daily_usage = document.getElementById('daily_usage');
    const med_img = document.getElementById('med_img');
    const monthly_usage = document.getElementById('monthly_usage');

    var chartData = document.getElementById('chartData');

    /* 모델별 평균 정확도 */
    new Chart(avg_acc, {
        plugins: [ChartDataLabels],
        type: 'bar',
        data: {
            labels: ['모델1', '모델2', '모델3'],
            datasets: [{
                label: '평균 정확도(%)',
                data: [70, 88, 64],
                datalabels: {
                    anchor: 'end',
                    align: 'start'
                }
            }]
        },
        options: {
            plugins: {
                tooltip: {
                    enabled: false
                },
                datalabels: {
                    color: 'black',
                    font: {
                        weight: 'bold',
                    }
                },
                title: {
                    display: true,
                    text: '모델별 평균 정확도',
                    font: {
                        size: 15
                    },
                },
                legend: {
                    position: 'bottom'
                }
            },
            maxBarThickness: 50,
            scales: {
                y: {
                    beginAtZero: true
                }
            },
        },

    });

    /* 태그 데이터 비율 */
    var taggedCnt = chartData.getAttribute('data-taggedCnt');
    var nonTaggedCnt = chartData.getAttribute('data-nonTaggedCnt');

    new Chart(tag_ratio, {
        plugins: [ChartDataLabels],
        type: 'doughnut',
        data: {
            labels: ['태그 데이터', '미태그 데이터'],
            datasets: [{
                data: [taggedCnt, nonTaggedCnt],
                datalabels: {
                    anchor: 'center'
                },
            }]
        },
        options: {
            plugins: {
                tooltip: {
                    enabled: false
                },
                datalabels: {
                    backgroundColor: function (context) {
                        return context.dataset.backgroundColor;
                    },
                    borderColor: 'white',
                    borderRadius: 25,
                    borderWidth: 2,
                    color: 'white',
                    display: function (context) {
                        var dataset = context.dataset;
                        var count = dataset.data.length;
                        var value = dataset.data[context.dataIndex]
                        return value
                    },
                    font: {
                        weight: 'bold',
                        size: 15
                    }
                },
                title: {
                    display: true,
                    text: '태그 데이터 비율',
                    font: {
                        size: 15
                    },
                },
                legend: {
                    position: 'bottom'
                }
            }
        }
    });

    /* 일일 사용량 */
    var dailyUsage = JSON.parse(chartData.getAttribute('data-dailyUsage'));
    var dailyLabels = dailyUsage.map(entry => entry[0]);
    var dailyDatas = dailyUsage.map(entry => entry[1]);

    new Chart(daily_usage, {
        plugins: [ChartDataLabels],
        type: 'line',
        data: {
            labels: dailyLabels,
            datasets: [{
                label: '일일 사용량',
                data: dailyDatas,
                datalabels: {
                    align: 'end',
                    anchor: 'end',
                },
                fill: true,
            }]
        },
        options: {
            plugins: {
                tooltip: {
                    enabled: false
                },
                datalabels: {
                    backgroundColor: function (context) {
                        return context.dataset.backgroundColor;
                    },
                    borderRadius: 4,
                    color: 'black',
                    font: {
                        weight: 'bold',
                        size: 15
                    },
                },
                title: {
                    display: true,
                    text: '일일 사용량',
                    font: {
                        size: 15
                    },
                },
                legend: {
                    position: 'bottom'
                }
            },

            scales: {
                y: {
                    beginAtZero: true,
                }
            }
        }
    });

    /* 의약품별 보유 이미지 */
    var medImgs = JSON.parse(chartData.getAttribute('data-medImgs'))
    var imgLabels = medImgs.map(entry => entry[0]);
    var imgDatas = medImgs.map(entry => entry[1]);

    new Chart(med_img, {
        plugins: [ChartDataLabels],
        type: 'bar',
        data: {
            labels: imgLabels,
            datasets: [{
                label: '개',
                data: imgDatas,
                datalabels: {
                    anchor: 'end',
                    align: 'start'
                }
            }]
        },
        options: {
            plugins: {
                tooltip: {
                    enabled: false
                },
                datalabels: {
                    color: 'black',
                    font: {
                        weight: 'bold',
                    }
                },
                title: {
                    display: true,
                    text: '의약품별 보유 이미지',
                    font: {
                        size: 15
                    },
                },
                legend: {
                    position: 'bottom'
                }
            },
            scales: {
                y: {
                    beginAtZero: true
                }
            },

        }
    });

    /* 월간 사용량 */
    var monthlyUsage = JSON.parse(chartData.getAttribute('data-monthlyUsage'));
    var monthlyLabels = monthlyUsage.map(entry => entry[0] + '월');
    var monthlyDatas = monthlyUsage.map(entry => entry[1]);

    new Chart(monthly_usage, {
        plugins: [ChartDataLabels],
        type: 'line',
        data: {
            labels: monthlyLabels,
            datasets: [{
                label: '월별 사용량',
                data: monthlyDatas,
                datalabels: {
                    align: 'end',
                    anchor: 'end',
                },
                fill: true,
            }]
        },
        options: {
            plugins: {
                tooltip: {
                    enabled: false
                },
                datalabels: {
                    backgroundColor: function (context) {
                        return context.dataset.backgroundColor;
                    },
                    borderRadius: 4,
                    color: 'black',
                    font: {
                        weight: 'bold',
                        size: 15
                    },
                },
                title: {
                    display: true,
                    text: '월간 사용량',
                    font: {
                        size: 15
                    },
                },
                legend: {
                    position: 'bottom'
                }
            },
            scales: {
                y: {
                    beginAtZero: true,
                }
            }
        }
    });

</script>
{% endblock %}

server/templates/page/medicine_list.html
{% extends 'base.html' %}
{% block content %}

<h2 class="border-bottom py-3 m-3">의약품 관리</h2>

<div class="py-3 m-3">

    <div class="row p-3">
        <div class="col-5 p-3">
            <!-- 검색 -->
            <div class="input-group mb-3">
                <input type="text" id="search_kw" class="form-control me-1" value="{{ kw or ''}}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">검색</button>
                </div>
            </div>

            <!-- 태깅된 약품 목록 -->
            <div class="text-end mb-2">
                <a class="btn btn-outline-success btn-sm" href="{{ url_for('page.medicine_download_csv', tbType='tagged') }}">
                    <i class="bi bi-download"></i> 엑셀 다운로드
                </a>
            </div>

            <div class="mb-5" style="max-height: 400px; overflow-y: auto;">
                <table class="table table-hover table-bordered taggedTable">
                    <thead class="sticky-top">
                        <tr class="text-center table-primary">
                            <th>번호</th>
                            <th>약품명</th>
                            <th>유형</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% if t_medicine_list %}
                        {% for medicine in t_medicine_list %}
                        <tr class="text-center" data-medId="{{ medicine.med_id }}">
                            <td>{{ loop.index0 + 1 }}</td>
                            <td class="text-center">{{ medicine.name }}</td>
                            <td>
                                {% if medicine.effect_type == 'N' %}
                                약품
                                {% elif medicine.effect_type == 'K' %}
                                키트
                                {% else %}
                                기타
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="3" class="text-center">약품 정보가 없습니다.</td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>

            <!-- 미태깅 약품 목록 -->
            <div class="text-end mb-2">
                <a class="btn btn-outline-success btn-sm" href="{{ url_for('page.medicine_download_csv', tbType='nonTagged') }}">
                    <i class="bi bi-download"></i> 엑셀 다운로드
                </a>
            </div>

            <table class="table table-hover table-bordered nonTaggedTable">
                <thead>
                    <tr class="text-center table-primary">
                        <th>번호</th>
                        <th>약품명</th>
                        <th>유형</th>
                    </tr>
                </thead>

                <tbody>
                    {% if nt_medicine_list.total %}
                    {% for medicine in nt_medicine_list.items %}
                    <tr class="text-center" data-medId="{{ medicine.med_id }}">
                        <td>{{ loop.index0 + 1 + (nt_medicine_list.page - 1) * nt_medicine_list.per_page }}</td>
                        <td class="text-center">{{ medicine.name }}</td>
                        <td>
                            {% if medicine.effect_type == 'N' %}
                            약품
                            {% elif medicine.effect_type == 'K' %}
                            키트
                            {% else %}
                            기타
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td colspan="3" class="text-center">약품 정보가 없습니다.</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>

        </div>

        <!-- 약품 상세 정보 -->
        <div class="col-6 p-3 ms-4">
            <div class="card">
                <div class="card-body">
                    <div class="mb-3">
                        <p class="fw-bold" id="name"></p>
                    </div>

                    <div class="mb-3">
                        <label for="effect">효능</label>
                        <textarea class="form-control" id="effect" rows="3" style="resize:none;" readonly></textarea>
                    </div>

                    <div class="mb-3">
                        <label for="usage">용법</label>
                        <textarea class="form-control" id="usage" rows="3" style="resize:none;" readonly></textarea>
                    </div>

                    <div class="mb-3">
                        <label for="caution">주의사항</label>
                        <textarea class="form-control" id="caution" rows="6" style="resize:none;" readonly></textarea>
                    </div>

                    <div class="text-end">
                        <a href="javascript:void(0)" class="btn btn-primary d-none" id="addTagBtn">
                            태그 추가
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- 페이징 -->
    <ul class="pagination justify-content-center mt-5">
        <!-- 이전 페이지 -->
        {% if nt_medicine_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ nt_medicine_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}

        <!-- 숫자 페이지 -->
        {% for page_num in nt_medicine_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != nt_medicine_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}

        <!-- 다음 페이지 -->
        {% if nt_medicine_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ nt_medicine_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>


</div>

<!-- 검색 폼 -->
<form id="searchForm" method="get" action="{{ url_for('page.medicine_list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{% endblock %}
{% block script %}
<script type="text/javascript">

    /* 페이징 */
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function (element) {
        element.addEventListener('click', function () {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });

    /* 검색 */
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function () {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1; // 검색 시 1페이지부터 조회
        document.getElementById('searchForm').submit();
    })

    const search_kw = document.getElementById("search_kw");
    search_kw.addEventListener('keyup', function (event) {
        if (event.key === "Enter") {
            document.getElementById('kw').value = search_kw.value;
            document.getElementById('page').value = 1; // 검색 시 1페이지부터 조회
            document.getElementById('searchForm').submit();
        }
    });

    /* 약품 상세 정보(AJAX) */
    const rows = document.querySelectorAll('tr[data-medId]');
    const nameArea = document.getElementById('name');
    const effectTextarea = document.getElementById('effect');
    const usageTextarea = document.getElementById('usage');
    const cautionTextarea = document.getElementById('caution');

    var medId;
    const addTagBtn = document.getElementById("addTagBtn");

    let selectedRow = null

    function adjustTextareaHeight(textarea) {
        textarea.style.height = 'auto';
        textarea.style.height = (textarea.scrollHeight) + 'px';

    }

    rows.forEach(function (row) {
        row.addEventListener('click', function () {
            // const medId = this.getAttribute('data-medId');
            medId = this.getAttribute('data-medId');
            console.log(medId)
            
            const tableType = row.closest('table').classList.contains('taggedTable') ? 'tagged' : 'nonTagged';

            if (selectedRow) {
                selectedRow.classList.remove('table-active');
            }

            selectedRow = this;
            selectedRow.classList.add('table-active');

            fetch(`/page/medicine_detail/${medId}`)
                .then(response => response.json())
                .then(data => {
                    if ('error' in data) {
                        console.error(data.error);
                    } else {
                        nameArea.textContent = data.name;
                        effectTextarea.value = data.effect;
                        usageTextarea.value = data.usage;
                        cautionTextarea.value = data.caution;

                        /*
                        adjustTextareaHeight(effectTextarea);
                        adjustTextareaHeight(usageTextarea);
                        adjustTextareaHeight(cautionTextarea);
                        */
                        

                        if (tableType == 'nonTagged') {
                            addTagBtn.classList.remove('d-none');
                        } else {
                            addTagBtn.classList.add('d-none');
                        }
                    }
                })
                .catch(error => {
                    console.error('약품 정보를 가져오는 중 오류 발생: ', error)
                });
        });
    });

    /* 태그 추가 */
    addTagBtn.addEventListener('click', function() {
        
        if(medId && confirm("태그를 추가하시겠습니까?")) {
            window.location.href = `/page/medicine_add_tag/${medId}`
        }

    })

</script>
{% endblock %}